services:
    app:
        container_name: password_manager
        build: 
            context: .
            dockerfile: docker-files/app/DockerFile
        ports:
            - "8000:8000"
        volumes:
            - ./src:/app

    