[tool.poetry]
name = "password-manager"
version = "0.1.0"
description = ""
authors = ["ZeroRangee <djermeer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"
podman = "^5.2.0"
podman-compose = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
