FROM python:3.12-alpine3.20

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk add --no-cache gcc musl-dev libffi-dev

RUN pip install --no-cache-dir poetry




COPY src/. /poetry.lock /pyproject.toml /app/

RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi --no-root




