


server {
    listen 443 ssl;
    server_name password-manager.local;

    ssl_certificate /etc/nginx/certs/local.crt;
    ssl_certificate_key /etc/nginx/certs/local.key;

    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
    location /mail/ {
        proxy_pass http://maildev:1080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

}

server {
    listen 25;  # SMTP порт для почт

    # ssl_certificate /etc/nginx/certs/local.crt;
    # ssl_certificate_key /etc/nginx/certs/local.key;

    
}
   



