# Generated by Django 5.1.4 on 2025-01-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrypassword",
            name="website_url",
            field=models.URLField(max_length=255),
        ),
    ]
